version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
  ignore:
    - dependency-name: "rspec-rails"
    - dependency-name: "rubocop*"
  open-pull-requests-limit: 5
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
